apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 66.0.0
    helm:
      values: |
        grafana:
          adminPassword: Aa123456
          grafana.ini:
            security:
              allow_embedding: true
            server:
              root_url: http://localhost:3000
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            serviceMonitorSelector: {}
            serviceMonitorNamespaceSelector: {}
            retention: 2d
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
